apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-

commonLabels:
    app: my-app
    env: stage

bases:
  - ../../base


patchesStrategicMerge:
  - deployment.yaml

namespace: staging