apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: demo-

commonLabels:
    app: my-app
    env: demo

bases:
  - ../../base


patchesStrategicMerge:
  - deployment.yaml

namespace: demo